require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require './lib/enigma'
require './lib/encryptor'
require './lib/keygen'
require './lib/decryptor'
require './lib/shifter'
require './lib/aggregator'
require 'pry'
require 'date'
